image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn -Pprod package -DskipTests"
  artifacts:
    paths:
      - target/*.war

docker-build:
  stage: package
  script:
  - docker build -t registry.gitlab.com/voldemortapp/voldemort-backend .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/voldemortapp/voldemort-backend

k8s-deploy:
  image: google/cloud-sdk
  stage: deploy
  script:
  - echo "$GOOGLE_KEY" > key.json
  - gcloud auth activate-service-account --key-file key.json
  - gcloud config set compute/zone us-central1-a
  - gcloud config set project pishe-231414
  - gcloud config set container/use_client_certificate True
  - gcloud container clusters get-credentials pishe-cluster-1
  - kubectl delete secret registry.gitlab.com  --ignore-not-found
  - kubectl create secret docker-registry registry.gitlab.com --docker-server=https://registry.gitlab.com/v1/ --docker-username="$CI_REGISTRY_USER" --docker-password="$CI_REGISTRY_PASSWORD" --docker-email=i@ehdi.in
  - kubectl create -f mariadb.yaml
  - kubectl apply -f deployment.yml



