stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn -Pprod package -DskipTests"
  artifacts:
    paths:
      - target/*.war

docker-build:
  stage: package
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u $PISHE_USER -p $PISHE_PASS $CI_REGISTRY
  - docker build --pull -t $IMAGE_URL:$TAG .
  - docker push $IMAGE_URL:$TAG

docker-deploy:
    stage: deploy
    environment:
        name: production
        url: http://pishehr.ir
    script:
        - eval $(ssh-agent -s)
        - bash -c 'ssh-add <(echo "${SSH_PRIVATE_KEY}")'
        - mkdir -p ~/.ssh
        - echo "${SSH_HOST_KEY}" > ~/.ssh/known_hosts
        - ssh-add <(echo "$SSH_PRIVATE_KEY")
        - ssh pishe@pishehr.ir 'cd /home/pishe/ && docker-compose down && docker-compose pull && docker-compose up -d && exit'
