stages:
  - build
  - package

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn -Pprod package -DskipTests"
  artifacts:
    paths:
      - target/*.war

docker-build:
  stage: package
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u $PISHE_USER -p $PISHE_PASS $CI_REGISTRY
  - docker build --pull -t $IMAGE_URL:$TAG .
  - docker push $IMAGE_URL:$TAG

