stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn -Pprod package -DskipTests"
  artifacts:
    paths:
      - target/*.war

docker-build:
  stage: package
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u $PISHE_USER -p $PISHE_PASS $CI_REGISTRY
  - docker build --pull -t $IMAGE_URL:$TAG .
  - docker push $IMAGE_URL:$TAG

docker-deploy:
    stage: deploy
    environment:
        name: production
        url: http://pishehr.ir
    before_script:
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - mkdir -p ~/.ssh
        - eval $(ssh-agent -s)
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    script:
        - ssh-add <(echo "$SSH_PRIVATE_KEY")
        - ssh -o StrictHostKeyChecking=no root@pishehr.ir 'cd /home/pishe/ && docker-compose down && docker-compose pull && docker-compose up -d && exit'
