image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - push
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn -Pprod package -DskipTests"
  artifacts:
    paths:
      - target/*.war

docker-build:
  stage: package
  script:
  - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
  - docker build -t registry.gitlab.com/voldemortapp/voldemort-backend .
  - docker push $IMAGE_URL:$TAG

push:
  stage: push
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
  - docker build --pull -t $IMAGE_URL:$TAG .
  - docker push $IMAGE_URL:$TAG
  only:
  - master

deploy:
  stage: deploy
  image: python:3.5
  variables:
    COLLECT_ERROR: 1
  script:
  - pip install fandogh_cli --upgrade
  - fandogh login --username $FAN_USR --password $FAN_PASS
  - ./deployment/scripts/deploy-to-fandogh.sh
  only:
  - master
