version: '2'
services:
    voldemort-app:
        image: voldemort
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://voldemort-mariadb:3306/voldemort
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    voldemort-mariadb:
        extends:
            file: mariadb.yml
            service: voldemort-mariadb
