package io.avand.domain.enumeration;

public enum PermissionAccess {
    ADD_CANDIDATE,
    VIEW_CANDIDATE,
    EDIT_CANDIDATE,
    DELETE_CANDIDATE,
    ASSIGN_CANDIDATE_TO_JOB,
    EDIT_CANDIDATE_PIPELINE,
    ADD_JOB,
    VIEW_JOB,
    EDIT_JOB,
    EDIT_JOB_STATUS,
    DELETE_JOB,
    EDIT_COMPANY,
    ADD_FEEDBACK,
    VIEW_FEEDBACK,
    EDIT_FEEDBACK,
    DELETE_FEEDBACK,
    ADD_COMMENT,
    VIEW_COMMENT,
    EDIT_COMMENT,
    DELETE_COMMENT,
    ADD_SCHEDULE,
    VIEW_SCHEDULE,
    EDIT_SCHEDULE,
    DELETE_SCHEDULE
}
